ControllerAdvisor modified to allow custom modification of log level …
BitWeb/java-core-lib pull request #9
Opened 2024-02-12 10:39 UTC by Jorich

ControllerAdvisor modified to allow custom modification of log level for EntityNotFound and Conflict exception.
Amqp autoconfiguration fixed to not fluch MDC on Exception before ErrorHandler can log errors.

2024-02-12 12:52 UTC, rammrain requested changes

2024-02-12 12:52 UTC, rammrain commented on src/main/java/ee/bitweb/core/api/ControllerAdvisor.java
> +        log(properties.getLogging().getConflictException(), e.getMessage(), e);
Minu arust on siin hetkel konflikne olukord. Handler on `PersistenceException`'i jaoks, aga kasutame `ConflictException`'i levelit. Konflik tekib just siis, kui kasutaja on ise defineerinud oma erindi mis laiendab `ConflictException`i.

2024-02-12 12:52 UTC, rammrain commented on src/main/java/ee/bitweb/core/api/ControllerAdvisorProperties.java
> +        @Deprecated(since = "3.1.0", forRemoval = true)
Võiks panna javadoc kommentaari ka, et deprecated ja kasutaja teisi välju

2024-02-12 13:03 UTC, Jorich commented on src/main/java/ee/bitweb/core/api/ControllerAdvisor.java
> +        log(properties.getLogging().getConflictException(), e.getMessage(), e);
Jep, energiajoogisena mõte jooksis kiiremini eest ära kui käed jõudsid järgi. Parandus tehtud

2024-02-13 08:45 UTC, rammrain submitted a review, later dismissed

2024-02-13 11:02 UTC, pr11t submitted a review, later dismissed

2024-02-14 08:18 UTC, pr11t approved these changes

2024-02-14 08:29 UTC, rammrain approved these changes

2024-02-19 06:41 UTC, merged